### ISSUE TITLE
Build instructions missing or outdated in README

### ISSUE THREAD

**Issue by phaedon** [mcneel/RhinoUSD#37]
Hi, is this the plugin of record for importing USD files in Rhino (8 or 7)?

The README mentions a Visual Studio solution (`.sln`) file, but it's not directly present in this repository, nor are there instructions on possibly how to generate such a solution file (nor any self-explanatory scripts using CMake / Bazel / other common build generator systems).

Please advise on next steps.

**Comment by sbaer** [comment]
I updated
`The solution contains the following projects`
to
`The repository contains the following projects`
in the readme.md.

These are the import and export USD plug-ins for Rhino. The export plug-in is currently built and ships with Rhino. The import plug-in does not have an implementation yet and is where we will be adding code to support import in the future
